### ISSUE TITLE
Pdf Practica hilos

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-de-hilos-IsraelNicolas61#2]
[Practica Individual HILOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-IsraelNicolas61/files/6513249/Practica.Individual.HILOS.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19.4/20

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 20/20.

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
